[package]
name = "bizarre"
version = "0.1.0"
authors = ["Alex Adewole <alex@bizar.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.17.4"