name: "Alex Adewole"
#status: 
#  - "📚 studying comp sci"
#  - "💻 building cool stuff"
#  - "📸 taking photos"
bio: >
  hi im alex, i write code and take photos. 😎
journal_subtitle: unfiltered musings, sometimes related to tech.
sketches_subtitle: visual representations of math & other cool stuff.